version: "3"

services:
  monip:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    extends:
      file: common-services.yml
      service: monip
    ports:
      - "8081:3000"

    volumes:
      - ./:/service
